/-
Copyright (c) 2024 OrdinalAutoFormalization Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: [Your Name]
-/
import OrdinalHomeo.Basic
import OrdinalHomeo.Moiety
import OrdinalHomeo.DegreeOne.PerfectGroups

/-!
# Normal Generators for Degree One Homeomorphism Groups

This file proves that Homeo(ω^(α+1)) can be normally generated by a single element
(or by 2 elements if we want a specific type of generator).

## Main definitions

* `NormalGenerates`: A set normally generates a group
* `UniformNormalGenerator`: Elements with uniform normal generation property

## Main results

* `anderson_method`: Elements displacing moieties generate all moiety-supported elements
* `normal_generator_exists`: Any element inducing an infinite permutation normally generates
* `two_normal_generators`: Two specific elements normally generate Homeo(ω^(α+1))

## References

* [Bhat et al., Algebraic and geometric properties of homeomorphism groups of ordinals]
-/

namespace OrdinalHomeo

open Ordinal Topology Set

universe u

section NormalGenerators

/-- A set S normally generates a group G if the normal closure of S equals G -/
def NormalGenerates {G : Type*} [Group G] (S : Set G) : Prop :=
  Subgroup.normalClosure S = ⊤

/-- An element g uniformly normally generates if there's a bound on conjugates needed -/
structure UniformNormalGenerator {G : Type*} [Group G] (g : G) where
  k : ℕ
  generates : ∀ h : G, ∃ (conj : Fin k → G) (powers : Fin k → ℤ),
    h = (List.ofFn (fun i : Fin k => (conj i)⁻¹ * (g ^ (powers i : ℤ)) * (conj i))).prod

/-- Anderson's method: Elements displacing moieties generate all moiety-supported elements -/
theorem anderson_method {α : Ordinal.{u}} {h : H α 1} (_A : TopologicalMoiety α)
  (_hDisjoint : h.toFun '' (_A : Set (X α 1)) ∩ (_A : Set (X α 1)) = ∅) :
  ∀ f : H α 1, ∀ B : TopologicalMoiety α, support f ⊆ (B : Set (X α 1)) →
    ∃ (conj : Fin 4 → H α 1) (powers : Fin 4 → ℤ),
      f = (List.ofFn (fun i : Fin 4 => (conj i)⁻¹ * (h ^ (powers i : ℤ)) * (conj i))).prod := by
  sorry

/-- Elements inducing infinite permutations displace some moiety -/
lemma infinite_permutation_displaces_moiety {α : Ordinal.{u}} {h : H α 1}
  (_hInf : Set.Infinite {x ∈ maximalRankElements α 1 | h.toFun x ≠ x}) :
  ∃ A : TopologicalMoiety α, h.toFun '' (A : Set (X α 1)) ∩ (A : Set (X α 1)) = ∅ := by
  sorry

/-- Main theorem: Elements inducing infinite permutations normally generate -/
theorem infinite_permutation_normal_generator {α : Ordinal.{u}} {h : H α 1}
  (_hInf : Set.Infinite {x ∈ maximalRankElements α 1 | h.toFun x ≠ x}) :
  NormalGenerates {h} := by
  sorry

/-- Two elements normally generate if one permutes infinitely and the other swaps moieties -/
theorem two_normal_generators {α : Ordinal.{u}} (_h₁ h₂ : H α 1)
  (_h₁_inf : Set.Infinite {x ∈ maximalRankElements α 1 | _h₁.toFun x ≠ x})
  (_h₂_invol : Function.Involutive h₂.toFun) 
  (_h₂_moiety : ∃ A : TopologicalMoiety α, h₂.toFun '' (A : Set (X α 1)) = (A : Set (X α 1))ᶜ) :
  NormalGenerates {_h₁, h₂} := by
  sorry

/-- For specific ordinals, we can achieve normal generation with a single element -/
theorem single_normal_generator_exists (_α : Ordinal.{u}) :
  ∃ h : H _α 1, NormalGenerates {h} := by
  sorry

/-- Corollary: The minimal cardinality of a normal generating set is 1 -/
theorem minimal_normal_generators (α : Ordinal.{u}) : 
  ∃ (S : Finset (H α 1)), S.card = 1 ∧ NormalGenerates (S : Set (H α 1)) := by
  obtain ⟨h, hGen⟩ := single_normal_generator_exists α
  use {h}
  constructor
  · simp
  · convert hGen
    simp

end NormalGenerators

end OrdinalHomeo