/-
Copyright (c) 2024 OrdinalAutoFormalization Authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: [Your Name]
-/
import OrdinalHomeo.Basic
import OrdinalHomeo.Moiety
import Mathlib.Data.Real.Basic

/-!
# Strong Distortion of Homeomorphism Groups

This file proves that Homeo(ω^(α+1)) is strongly distorted, a property stronger than
strong boundedness that implies many geometric constraints.

## Main definitions

* `StronglyDistorted`: A group with uniformly bounded finite generation for sequences
* `StronglyBounded`: Every left-invariant metric has bounded diameter
* `CalegariFreedmanConstruction`: The construction for proving strong distortion

## Main results

* `homeo_strongly_distorted`: Homeo(ω^(α+1)) is strongly distorted
* `strong_distortion_implies_strong_boundedness`: Strong distortion implies strong boundedness
* `higher_degree_not_distorted`: H_{α,d} for d > 1 is not strongly distorted

## References

* [Bhat et al., Algebraic and geometric properties of homeomorphism groups of ordinals]
-/

namespace OrdinalHomeo

open Ordinal Topology Set

universe u

section StrongDistortion

/-- A group is strongly distorted if sequences have uniformly bounded generation -/
class StronglyDistorted (G : Type*) [Group G] where
  m : ℕ
  width : ℕ → ℕ
  generation : ∀ (g : ℕ → G), ∃ S : Finset G, S.card ≤ m ∧ 
    ∀ n, g n ∈ {x | ∃ (f : Fin (width n) → G), (∀ i, f i ∈ S) ∧ x = (List.ofFn f).prod}

/-- A group is strongly bounded if every left-invariant metric has bounded diameter -/
def StronglyBounded (G : Type*) [Group G] : Prop :=
  ∀ d : G → G → ℝ, (∀ g h k, d (g * h) (g * k) = d h k) → 
    (∀ g h, d g h ≥ 0) → (∀ g, d g g = 0) →
    ∃ M, ∀ g h, d g h ≤ M

/-- The Calegari-Freedman construction for proving strong distortion -/
lemma calegari_freedman_construction {α : Ordinal.{u}} 
  (A B : TopologicalMoiety α)
  (σ : H α 1) (hσ : IsConvergentATranslation A σ ∧ support σ ⊆ (B : Set (X α 1)))
  (τ : H α 1) (hτ : IsConvergentATranslation B τ) :
  ∀ (h : ℕ → H α 1), (∀ n, support (h n) ⊆ (A : Set (X α 1))) →
    ∃ φ ψ : H α 1, ∀ n, h n = φ * (τ^n) * ψ * (τ^n)⁻¹ * φ⁻¹ := by
  intro h h_supp
  -- The idea: since σ is an A-translation with support in B, and τ is a B-translation,
  -- we can use conjugation by powers of τ to "move" the support of h_n
  -- This is the key insight of Calegari-Freedman
  
  -- Step 1: Define φ using the fact that σ translates A convergently
  -- Since h_n has support in A and σ moves A, we can arrange things so that
  -- the conjugates τ^n σ τ^{-n} have disjoint supports for different n
  
  -- Step 2: Define ψ to encode the sequence h using these disjoint conjugates
  -- The disjointness ensures we can define a homeomorphism that acts like h_n
  -- on the n-th translate
  
  sorry  -- Requires: detailed construction using convergent translations

/-- Main theorem: Homeo(ω^(α+1)) is strongly distorted -/
instance homeo_strongly_distorted (α : Ordinal.{u}) : 
  StronglyDistorted (H α 1) := by
  sorry

/-- Strong distortion implies strong boundedness -/
theorem strong_distortion_implies_strong_boundedness {G : Type*} [Group G]
  [inst : StronglyDistorted G] : StronglyBounded G := by
  -- Let d be a left-invariant metric on G
  intro d h_inv h_nonneg h_zero
  -- We need to show d has bounded diameter
  -- By strong distortion, there exists m and width such that any sequence
  -- can be generated by at most m elements with bounded word length
  have ⟨m, width, h_gen⟩ := inst
  -- The key is that any g ∈ G appears in some sequence, so has bounded word length
  -- with respect to a finite generating set
  sorry  -- Requires: connecting sequence generation to metric boundedness

/-- For d > 1, H_{α,d} is not strongly distorted -/
theorem higher_degree_not_distorted {α : Ordinal.{u}} {d : ℕ} (hd : d > 1) :
  ¬ Nonempty (StronglyDistorted (H α d)) := by
  sorry

/-- Corollary: Classification by strong distortion -/
theorem distortion_classification (α : Ordinal.{u}) (d : ℕ) :
  (Nonempty (StronglyDistorted (H α d)) ↔ d = 1) ∧
  (StronglyBounded (H α d) ↔ d = 1) := by
  sorry

end StrongDistortion

end OrdinalHomeo